import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MRX
 */
public class frame1 extends javax.swing.JFrame {
    int choice,z,pin=1234,counter=1,a=3;

    /**
     * Creates new form frame1
     */
    public frame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfPin = new javax.swing.JTextField();
        jbEnter = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("BOJONEGORO");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(120, 80, 140, 40);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Masukkan 6 Digit Pin Anda ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 110, 240, 40);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("ATM BNI SYARIAH");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(100, 50, 190, 40);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Selamat Datang Di");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(110, 20, 150, 40);
        jPanel1.add(tfPin);
        tfPin.setBounds(30, 150, 320, 40);

        jbEnter.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbEnter.setText("ENTER");
        jbEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEnterActionPerformed(evt);
            }
        });
        jPanel1.add(jbEnter);
        jbEnter.setBounds(110, 200, 150, 40);

        jLabel5.setText("Pass : 000209");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 270, 80, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setBounds(0, 0, 580, 464);
    }// </editor-fold>//GEN-END:initComponents

    private void jbEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEnterActionPerformed
        if(tfPin.getText().trim().equals("000209")) {
        javax.swing.JOptionPane.showMessageDialog(null, "Selamat Datang");
        new frame2().setVisible(true);
        this.dispose();
    }
        else if (counter<3) {
            a--;
            javax.swing.JOptionPane.showMessageDialog(null,"Pin Salah!\nPastikan"
                    + "PIN yang anda masukkan benar","ERROR",0);
            javax.swing.JOptionPane.showMessageDialog(null,"\nKesempatan login " +
                    a + " Kali lagi" + "\n");
            
            if(a==0){
                System.exit(0);
            }
        }
    }//GEN-LAST:event_jbEnterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbEnter;
    private javax.swing.JTextField tfPin;
    // End of variables declaration//GEN-END:variables
}
